import argparse
import time
import pandas as pd
import requests
import os
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

# Add project root to allow absolute imports
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(PROJECT_ROOT)

from src.utils.config_loader import get_project_root

def make_request(user_id, base_url="http://localhost:8000"):
    """
    Makes a single request to the recommend API and returns its latency.
    """
    url = f"{base_url}/recommend/{user_id}"
    start_time = time.time()
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for bad status codes (4xx or 5xx)
        latency_ms = (time.time() - start_time) * 1000
        # print(f"SUCCESS: uid={user_id}, status={response.status_code}, latency={latency_ms:.2f}ms")
        return "success", latency_ms
    except requests.exceptions.RequestException as e:
        latency_ms = (time.time() - start_time) * 1000
        print(f"FAILED: uid={user_id}, error={e}, latency={latency_ms:.2f}ms")
        return "failed", latency_ms

def run_stress_test(num_users, concurrency):
    """
    Runs a stress test against the recommendation API.
    """
    print(f"--- Starting Stress Test ---")
    print(f"Total Users: {num_users}")
    print(f"Concurrency Level: {concurrency}")
    print("----------------------------")

    # 1. Load user IDs from test data
    try:
        root_dir = get_project_root()
        # Assuming test.csv is generated by the data pipeline
        test_file_path = os.path.join(root_dir, 'data', 'processed', 'test.csv')
        df_test = pd.read_csv(test_file_path)
        # Ensure unique users and take a sample
        all_user_ids = df_test['uid'].unique()
        if num_users > len(all_user_ids):
            print(f"Warning: Requested {num_users} users, but only {len(all_user_ids)} unique users found in test.csv. Using all available users.")
            num_users = len(all_user_ids)
        
        user_ids_to_test = all_user_ids[:num_users]
    except FileNotFoundError:
        print(f"Error: test.csv not found at {test_file_path}. Please run the data pipeline first.")
        return

    # 2. Run tests in parallel
    latencies = []
    success_count = 0
    failure_count = 0
    
    total_start_time = time.time()
    
    with ThreadPoolExecutor(max_workers=concurrency) as executor:
        # Create a future for each request
        future_to_uid = {executor.submit(make_request, uid): uid for uid in user_ids_to_test}
        
        for i, future in enumerate(as_completed(future_to_uid)):
            uid = future_to_uid[future]
            try:
                status, latency = future.result()
                if status == "success":
                    latencies.append(latency)
                    success_count += 1
                else:
                    failure_count += 1
            except Exception as exc:
                print(f"Request for uid {uid} generated an exception: {exc}")
                failure_count += 1
            
            # Print progress
            print(f"Progress: {i+1}/{num_users}", end='\r')

    total_time_taken = time.time() - total_start_time

    # 3. Print summary
    print("\n--- Stress Test Summary ---")
    if latencies:
        avg_latency = sum(latencies) / len(latencies)
        max_latency = max(latencies)
        min_latency = min(latencies)
        
        # Calculate throughput (requests per second)
        throughput = num_users / total_time_taken

        print(f"Total Requests: {num_users}")
        print(f"Concurrency Level: {concurrency}")
        print(f"Total Time Taken: {total_time_taken:.2f} seconds")
        print(f"Throughput: {throughput:.2f} req/s")
        print("---")
        print(f"Successful Requests: {success_count}")
        print(f"Failed Requests: {failure_count}")
        print("---")
        print(f"Average End-to-End Latency: {avg_latency:.2f} ms")
        print(f"Min Latency: {min_latency:.2f} ms")
        print(f"Max Latency: {max_latency:.2f} ms")
    else:
        print("No successful requests were made.")
    print("---------------------------")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run a stress test on the recommendation API.")
    parser.add_argument(
        "--num-users",
        type=int,
        default=100,
        help="Number of unique users to test from test.csv."
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=10,
        help="Number of parallel requests to make."
    )
    args = parser.parse_args()

    run_stress_test(args.num_users, args.concurrency)
